export enum ReportType {
  DAILY_REGISTRATIONS = 'DAILY_REGISTRATIONS',
  DAILY_ATTENDANCE = 'DAILY_ATTENDANCE',
  DAILY_REVENUE = 'DAILY_REVENUE',
  WEEKLY_SUMMARY = 'WEEKLY_SUMMARY',
  MONTHLY_SUMMARY = 'MONTHLY_SUMMARY',
  FINANCIAL_SUMMARY = 'FINANCIAL_SUMMARY',
  CERTIFICATE_SUMMARY = 'CERTIFICATE_SUMMARY',
  EVENT_FINAL_REPORT = 'EVENT_FINAL_REPORT',
}
